Add missing includes to fix build with clang-r563880
The latest compiler is stricter with the includes.

pckages/providers/MediaProvider/pdf/framework/libs/pdfClient/page_object.h:61:21: error: no member named 'max' in namespace 'std'
   61 |         return std::max({abs(a - other.a), abs(b - other.b), abs(c - other.c), abs(d - other.d),
      |                ~~~~~^

Test: presubmit
Bug: 401330760
Flag: EXEMPT, dead code removal
Change-Id: Ic394917d339cdad275c14d3a409c13edc14a02af